# Generated by Django 6.0.3 on 2026-03-09 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nivel', models.IntegerField(choices=[(1, 'Coordinación'), (2, 'Unidad'), (3, 'Sección')])),
                ('departamento_padre', models.ForeignKey(blank=True, help_text='Dejar vacío si es una Coordinación (nivel raíz)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='tareas.departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='tareas.municipio')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'ordering': ['municipio__nombre', 'nombre'],
                'unique_together': {('nombre', 'municipio')},
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=150)),
                ('es_jefe', models.BooleanField(default=False, help_text='Indica si este trabajador es el jefe/responsable de su departamento')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='miembros', to='tareas.departamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En Progreso'), ('CO', 'Completada'), ('CA', 'Cancelada')], default='PE', max_length=2)),
                ('prioridad', models.CharField(choices=[('BJ', 'Baja'), ('ME', 'Media'), ('AL', 'Alta'), ('UR', 'Urgente')], default='ME', max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_inicio_planificada', models.DateField(verbose_name='Fecha de inicio planificada')),
                ('fecha_fin_planificada', models.DateField(verbose_name='Fecha de culminación planificada')),
                ('fecha_fin_real', models.DateField(blank=True, help_text='Completar si la tarea finalizó en una fecha distinta a la planificada', null=True, verbose_name='Fecha de finalización real')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('asignada_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to='tareas.personal', verbose_name='Asignada a')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_creadas', to='tareas.personal', verbose_name='Creada por')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='tareas.departamento', verbose_name='Departamento responsable')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='tareas.municipio', verbose_name='Municipio')),
                ('parroquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='tareas.parroquia', verbose_name='Parroquia')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
