# Generated by Django 6.0.3 on 2026-03-11 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoVenezuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['estado__nombre', 'nombre'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='parroquia',
            options={'ordering': ['municipio__estado__nombre', 'municipio__nombre', 'nombre'], 'verbose_name': 'Parroquia', 'verbose_name_plural': 'Parroquias'},
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='tareas.estadovenezuela', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado_geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='tareas.estadovenezuela', verbose_name='Estado (Venezuela)'),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('nombre', 'estado')},
        ),
    ]
