# Generated by Django 4.2.24 on 2026-04-15 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0004_alter_personal_options_personal_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.CreateModel(
            name='HistorialMovimientoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('DE', 'Desactivación'), ('AC', 'Activación'), ('MO', 'Modificación'), ('OT', 'Otro')], default='OT', max_length=2)),
                ('razon', models.TextField(verbose_name='Razón / Motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='tareas.personal')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Movimiento',
                'verbose_name_plural': 'Historial de Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
