# Generated by Django 4.2.24 on 2026-04-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_personal_activo_historialmovimientopersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPER', 'Supervisor'), ('USER', 'Usuario Normal')], default='USER', max_length=10, verbose_name='Rol de Usuario'),
        ),
    ]
