# Generated by Django 4.2.24 on 2026-04-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_personal_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='porcentaje_avance',
            field=models.PositiveIntegerField(default=0, verbose_name='Porcentaje de avance'),
        ),
    ]
