# Generated by Django 4.2.30 on 2026-06-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_bitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin_planificada',
            field=models.DateTimeField(verbose_name='Fecha de culminación planificada'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, help_text='Completar cuando la tarea finalice. Por defecto toma la fecha y hora actual.', null=True, verbose_name='Fecha de finalización real'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio_planificada',
            field=models.DateTimeField(verbose_name='Fecha de inicio planificada'),
        ),
    ]
